In [10]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [11]:
sentences = ['I played Ghost of Tsushima',
        'Call of Duty Vanguard is great',
        'Max payne is a classic game',
        'Far Cry 6 is hard to play',
        'Started playing God of War recently']

In [12]:
voc_size = 10000

In [13]:
onehot = [one_hot(words,voc_size)for words in sentences] 
print(onehot)

[[5997, 156, 3512, 5285, 8555], [9087, 5285, 1604, 3277, 2689, 8618], [4642, 9851, 2689, 3465, 5685, 8316], [9395, 4689, 5886, 2689, 7293, 4323, 9095], [3619, 4984, 1044, 5285, 1600, 1039]]


In [14]:
sent_length = 8
embedded_docs = pad_sequences(onehot,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 5997  156 3512 5285 8555]
 [   0    0 9087 5285 1604 3277 2689 8618]
 [   0    0 4642 9851 2689 3465 5685 8316]
 [   0 9395 4689 5886 2689 7293 4323 9095]
 [   0    0 3619 4984 1044 5285 1600 1039]]


In [15]:
dim = 10

In [17]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 151ms/step
[[[ 0.01318933 -0.02985513 -0.01407761  0.02678466 -0.02674249
    0.04647132  0.02914133  0.00108344  0.02967635 -0.00925574]
  [ 0.01318933 -0.02985513 -0.01407761  0.02678466 -0.02674249
    0.04647132  0.02914133  0.00108344  0.02967635 -0.00925574]
  [ 0.01318933 -0.02985513 -0.01407761  0.02678466 -0.02674249
    0.04647132  0.02914133  0.00108344  0.02967635 -0.00925574]
  [ 0.04519296 -0.04518262  0.03503771  0.03188929  0.01654246
   -0.02037457  0.03950186 -0.02096545 -0.02530321 -0.04629028]
  [ 0.01313877  0.04042025 -0.03379594 -0.01295739  0.03070057
   -0.0147263  -0.01692505  0.01232708 -0.00679588 -0.03519361]
  [-0.00990838 -0.04039831 -0.01844467 -0.0464875  -0.01307371
   -0.03415431  0.0051434   0.02120192  0.04041311  0.02361337]
  [ 0.03864335  0.01409273  0.02012723 -0.02627254  0.01692123
   -0.03149142  0.03426763 -0.0254864  -0.04616511  0.01754434]
  [ 0.02849172 -0.01717527 -0.01043029  0.00122653  0.0077

In [20]:
embedded_docs[0]

array([   0,    0,    0, 5997,  156, 3512, 5285, 8555])

In [21]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 20ms/step
[[ 0.01318933 -0.02985513 -0.01407761  0.02678466 -0.02674249  0.04647132
   0.02914133  0.00108344  0.02967635 -0.00925574]
 [ 0.01318933 -0.02985513 -0.01407761  0.02678466 -0.02674249  0.04647132
   0.02914133  0.00108344  0.02967635 -0.00925574]
 [ 0.01318933 -0.02985513 -0.01407761  0.02678466 -0.02674249  0.04647132
   0.02914133  0.00108344  0.02967635 -0.00925574]
 [ 0.04519296 -0.04518262  0.03503771  0.03188929  0.01654246 -0.02037457
   0.03950186 -0.02096545 -0.02530321 -0.04629028]
 [ 0.01313877  0.04042025 -0.03379594 -0.01295739  0.03070057 -0.0147263
  -0.01692505  0.01232708 -0.00679588 -0.03519361]
 [-0.00990838 -0.04039831 -0.01844467 -0.0464875  -0.01307371 -0.03415431
   0.0051434   0.02120192  0.04041311  0.02361337]
 [ 0.03864335  0.01409273  0.02012723 -0.02627254  0.01692123 -0.03149142
   0.03426763 -0.0254864  -0.04616511  0.01754434]
 [ 0.02849172 -0.01717527 -0.01043029  0.00122653  0.00775498 -0.02998576
